const colors=[["紅色","#ff5964"],["黃色","#ffd43b"],["藍色","#4285f4"],["綠色","#48c774"],["橘色","#ff963f"],["紫色","#9a6be0"],["粉紅色","#ff8fba"],["咖啡色","#956344"],["黑色","#30343b"],["白色","#f7f7f7"]];
const shapes=[["圓形","circle"],["正方形","square"],["三角形","triangle"],["星形","star"],["長方形","rect"],["橢圓形","oval"],["菱形","diamond"],["愛心","heart"]];
const bpmf="ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦ".split("");
const daily=[["杯子","🥤"],["牙刷","🪥"],["湯匙","🥄"],["雨傘","☂️"],["鞋子","👟"],["襪子","🧦"],["帽子","🧢"],["書本","📕"],["鉛筆","✏️"],["剪刀","✂️"],["鑰匙","🔑"],["電話","☎️"],["時鐘","⏰"],["燈","💡"],["床","🛏️"],["椅子","🪑"],["肥皂","🧼"],["毛巾","🧻"],["背包","🎒"],["碗","🥣"]];
const body=[["眼睛","👀"],["耳朵","👂"],["鼻子","👃"],["嘴巴","👄"],["牙齒","🦷"],["舌頭","👅"],["手","✋"],["腳","🦶"],["手臂","💪"],["頭","🙂"],["頭髮","🧑‍🦱"],["膝蓋","🦵"],["心臟","❤️"],["大腦","🧠"],["骨頭","🦴"]];
function shapeSvg(t){let f="#ff7287",m={circle:`<circle cx="50" cy="50" r="38" fill="${f}"/>`,square:`<rect x="13" y="13" width="74" height="74" rx="9" fill="${f}"/>`,triangle:`<polygon points="50,8 93,88 7,88" fill="${f}"/>`,star:`<polygon points="50,5 61,37 95,37 67,57 78,91 50,70 22,91 33,57 5,37 39,37" fill="#ffc928"/>`,rect:`<rect x="8" y="25" width="84" height="52" rx="9" fill="${f}"/>`,oval:`<ellipse cx="50" cy="50" rx="44" ry="30" fill="${f}"/>`,diamond:`<polygon points="50,5 95,50 50,95 5,50" fill="${f}"/>`,heart:`<path d="M50 90 C15 66 5 46 14 27 C23 8 43 13 50 28 C57 13 77 8 86 27 C95 46 85 66 50 90Z" fill="${f}"/>`};return`<svg class="shapeSvg" viewBox="0 0 100 100">${m[t]}</svg>`}
window.UNITS={
color:{title:"🎨 顏色島",modes:["tap","drag","line"],data(){let bank=[];for(let r=0;r<4;r++)colors.forEach(x=>bank.push({answer:x[0],prompt:`請找出${x[0]}！`}));return{bank,all:colors.map(x=>x[0]),map:Object.fromEntries(colors)}},visual(v,d){return`<div class="ball" style="background:${d.map[v]}"></div>`}},
shape:{title:"🔺 形狀森林",modes:["tap","drag","line"],data(){let bank=[];for(let r=0;r<4;r++)shapes.forEach(x=>bank.push({answer:x[0],prompt:`請找出${x[0]}！`}));return{bank,all:shapes.map(x=>x[0]),map:Object.fromEntries(shapes)}},visual(v,d){return shapeSvg(d.map[v])}},
number:{title:"🔢 數字王國",modes:["tap","drag","line","trace"],data(){let all=Array.from({length:20},(_,i)=>String(i+1)),bank=[];for(let r=0;r<2;r++)all.forEach(v=>bank.push({answer:v,prompt:`請找出數字${v}！`}));return{bank,all}},visual(v){return`<div class="symbol">${v}</div>`},trace:true},
bpmf:{title:"🎈 注音樂園",modes:["tap","drag","line","trace"],data(){return{bank:bpmf.map(v=>({answer:v,prompt:`請找出注音${v}！`})),all:bpmf}},visual(v){return`<div class="symbol">${v}</div>`},trace:true},
daily:{title:"🏠 生活小達人",modes:["tap","drag","line"],data(){let all=daily.map(x=>x[0]),bank=[];for(let r=0;r<2;r++)daily.forEach(x=>bank.push({answer:x[0],prompt:`請找出${x[0]}！`}));return{bank,all,map:Object.fromEntries(daily)}},visual(v,d){return`<div class="emoji">${d.map[v]}</div>`}},
body:{title:"🧒 身體探險隊",modes:["tap","drag","line"],data(){let all=body.map(x=>x[0]),bank=[];for(let r=0;r<2;r++)body.forEach(x=>bank.push({answer:x[0],prompt:`請找出${x[0]}！`}));return{bank,all,map:Object.fromEntries(body)}},visual(v,d){return`<div class="emoji">${d.map[v]}</div>`}}
};